language: "python"
cache: "pip"
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - "pip install -e .[tests,release]"
script:
  - "pylama"
  - "pytest --cov-report="
after_success:
  - "coveralls"
  - "python setup.py publish"  # needs PYPI_USERNAME, PYPI_PASSWORD, GH_TOKEN
